# Generated by Django 4.0.4 on 2022-07-28 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='profile_img/')),
                ('info', models.TextField(blank=True, null=True)),
                ('followings', models.ManyToManyField(related_name='followers', to='users.profile')),
            ],
        ),
    ]
